build:
    tests:
        override:
            - true

    nodes:
        tests:
            environment:
                php:
                    version: 7.4
                    pecl_extensions:
                        - zip
        analysis:
            environment:
                php:
                    version: 7.4
                    pecl_extensions:
                        - zip
            tests:
                override: [php-scrutinizer-run]
filter:
    paths: [application/*]
    excluded_paths: 
        - 'application/views/*'
        - 'framework/yiilite.php'
    dependency_paths:
        - 'framework/'
        - 'application/helpers/adodb/*'
        - 'application/libraries/admin/http/*'
        - 'application/libraries/admin/pclzip/*'
        - 'application/extensions/*'
        - 'application/tests/*'
        - 'application/third_party/*'
        - 'third_party/*'
        - 'installer/*'
        - 'application/helpers/Zend/*'        
        - 'application/libraries/admin/Services_JSON.php'
checks:
    javascript: true 
    php:
        code_rating: true
        duplication: true
        one_class_per_file: true
tools:
    php_cs_fixer:
        enabled:              true
        config:
            level:            psr2
            lowercase_keywords: false
        filter:
            excluded_paths:
                - 'framework/*'
                - 'locale/*'
                - 'docs/*'
                - 'fonts/*'
                - 'third_party/*'
                - 'application/helpers/adodb/*'
                - 'application/helpers/Zend/*'        
                - 'application/libraries/admin/http/*'
                - 'application/libraries/admin/Services_JSON.php'
                - 'application/libraries/admin/pclzip/*'
                - 'application/extensions/*'
                - 'application/views/*'
                - 'application/third_party/*'
                - 'images/*'
                - 'styles/*'
                - 'styles-public/*'
                - 'templates/*'
                - 'themes/*'
                - 'tmp/*'
                - 'upload/*'
                - 'tests/*'
                - 'application/tests/*'
                
coding_style:
    php:    
        braces:
            classes_functions:
                class: new-line
                function: new-line
                closure: new-line
            if:
                opening: end-of-line
            for:
                opening: end-of-line
            while:
                opening: end-of-line
            do_while:
                opening: end-of-line
            switch:
                opening: end-of-line
            try:
                opening: end-of-line
        upper_lower_casing:
            constants:
                true_false_null: lower
