filter:
    excluded_paths: [framework/*, locale/*, docs/*, fonts/*, third_party/*, application/extensions/*, application/third_party/*, images/*, styles/*, styles-public/*, templates/*, themes/*, tmp/*, upload/*]
    paths: [application/*]
checks:
    php:
        code_rating: true
        duplication: true
        one_class_per_file: true
                