<?php

namespace ls\tests;

use PHPUnit\Framework\TestCase;

class TestCondition extends TestCase
{
    /**
     * Asserts that the generated criteria condition matches the expected pattern
     * when field placeholders are wrapped using various SQL identifier separators.
     * This method supports MySQL/MariaDB (`), MSSQL ([]), and PostgreSQL ("")
     * field-name quoting styles.
     *
     * @param string $criteriaCondition  The actual SQL condition generated by the system.
     * @param string $pattern            The expected condition pattern containing placeholders.
     * @param array  $placeholders       The placeholder name and value is the field name to be inserted.
     *
     * @return void|null
     */
    public function assertFieldConditions(string $criteriaCondition, string $pattern, array $placeholders)
    {
        $separators = [
            ['`', '`'],
            ['[', ']'], // MSSQL
            ['"', '"']  // PostgreSQL
        ];
        foreach ($separators as $sep) {
            $condition = $pattern;
            foreach ($placeholders as $key => $fieldname) {
                $placeholder = "[{$key}]";
                $condition = str_replace($placeholder, $sep[0] . $fieldname . $sep[1], $condition);
            }
            if (strpos($criteriaCondition, $condition) !== false) {
                return $this->assertTrue(true);
            }
        }

        return $this->assertTrue(false, "Unexpected condition: {$criteriaCondition}");
    }
}
