#!/usr/bin/php
<?php
if (!file_exists(__DIR__ . '/vendor/autoload.php')) {
    echo "Composer autoloader not detected. Attempting to run composer install...\n";
    chdir(__DIR__ . '/..');
    passthru("composer install", $return);
    if ($return !== 0) {
        die("Failed to run composer install, please do it manually.");
    } else {
        echo "Composer install OK\n";
    }

}
$loader = require_once(__DIR__ . '/vendor/autoload.php'); 
class_exists(Yii::class);
if (!isset($argv[0])) die("This must be run from the console.\n");

require_once(__DIR__ . '/helpers/globals.php');

$config = require __DIR__ . '/config/internal.php';
unset ($config['defaultController']);
unset ($config['config']);
Yii::createApplication(ConsoleApplication::class, $config)->run();
?>
