<?php
interface IWriter
{

    public function __construct(\ls\models\forms\FormattingOptions $options);
    /**
    * Writes the survey and all the responses it contains to the output
    * using the options specified in FormattingOptions.
    *
    * See Survey for information on loading a survey
    * and results from the database.
    *
    * @param Survey $survey
    * @param string $language
    */
    public function write(Survey $survey, $language, \Psr\Http\Message\StreamInterface $stream = null);

    /**
     * @return string The mime type of data generated by this writer.
     */
    public function getMimeType();

    /**
     * @return string A file name for the export generated by this writer.
     */
    public function getFileName(Survey $survey, $language);
}