export const languages = {
  ar: {
    description: 'Arabic',
    nativedescription: '&#1593;&#1614;&#1585;&#1614;&#1576;&#1610;&#1618;',
    rtl: true,
    dateformat: 2,
    radixpoint: 0,
    momentjs: 'ar',
  },
  eu: {
    description: 'Basque',
    nativedescription: 'Euskara',
    rtl: false,
    dateformat: 3,
    radixpoint: 1,
    momentjs: 'eu',
  },
  nl: {
    description: 'Dutch',
    nativedescription: 'Nederlands',
    rtl: false,
    dateformat: 2,
    radixpoint: 1,
    momentjs: 'nl',
  },
  en: {
    description: 'English',
    nativedescription: 'English',
    rtl: false,
    dateformat: 9,
    radixpoint: 0,
    momentjs: 'en',
  },
  fr: {
    description: 'French',
    nativedescription: 'Fran&#231;ais',
    rtl: false,
    dateformat: 5,
    radixpoint: 1,
    momentjs: 'fr',
  },
  de: {
    description: 'German',
    nativedescription: 'Deutsch',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
    momentjs: 'de',
  },
}
