<?php

/**
 * A collection of default data sets, like surveymenus and surveymenuentries
 *
 * This class is important for installation (all datasets will be inserted to database tables and
 * to reset to a default setting (if user want to...)
 */
class LsDefaultDataSets
{
    public static function getSurveyMenuEntryData()
    {
        $sOldLanguage = App()->language;
        App()->setLanguage('en');

        $headerArray = ['menu_id','user_id','ordering','name','title','menu_title','menu_description','menu_icon','menu_icon_type','menu_class','menu_link','action','template','partial','classes','permission','permission_grade','data','getdatamethod','language','active','changed_at','changed_by','created_at','created_by', 'showincollapse'];
        $basicMenues = [
            [
                1,
                null,
                1,
                'overview',
                gT('Survey overview', 'unescaped'),
                gT('Overview', 'unescaped'),
                gT('Open the general survey overview', 'unescaped'),
                'ri-bar-chart-horizontal-line',
                'remix',
                '',
                'surveyAdministration/view',
                '',
                '',
                '',
                '',
                '',
                '',
                '{"render": { "link": {"data": {"surveyid": ["survey","sid"]}}}}',
                '',
                'en-GB',
                1,
                date('Y-m-d H:i:s'),
                0,
                date('Y-m-d H:i:s'),
                0,
                0
            ],
            [
                1,
                null,
                2,
                'generalsettings',
                gT('General survey settings', 'unescaped'),
                gT('General', 'unescaped'),
                gT('Open general survey settings', 'unescaped'),
                'ri-tools-line',
                'remix',
                '',
                '',
                'updatesurveylocalesettings_generalsettings',
                'editLocalSettings_main_view',
                '/admin/survey/subview/accordion/_generaloptions_panel',
                '',
                'surveysettings',
                'read',
                null,
                'generalTabEditSurvey',
                'en-GB',
                1,
                date('Y-m-d H:i:s'),
                0,
                date('Y-m-d H:i:s'),
                0,
                1
            ],
            [
                1,
                null,
                3,
                'surveytexts',
                gT('Survey text elements', 'unescaped'),
                gT('Text elements', 'unescaped'),
                gT('Survey text elements', 'unescaped'),
                "ri-text-spacing",
                'remix',
                '',
                '',
                'updatesurveylocalesettings',
                'editLocalSettings_main_view',
                '/admin/survey/subview/tab_edit_view',
                '',
                'surveylocale',
                'read',
                null,
                'getTextEditData',
                'en-GB',
                1,
                date('Y-m-d H:i:s'),
                0,
                date('Y-m-d H:i:s'),
                0,
                1
            ],
            [
                1,
                null,
                4,
                'datasecurity',
                gT('Privacy policy settings', 'unescaped'),
                gT('Privacy policy', 'unescaped'),
                gT('Edit privacy policy settings', 'unescaped'),
                "ri-shield-line",
                'remix',
                '',
                '',
                'updatesurveylocalesettings',
                'editLocalSettings_main_view',
                '/admin/survey/subview/tab_edit_view_datasecurity',
                '',
                'surveylocale',
                'read',
                null,
                'getDataSecurityEditData',
                'en-GB',
                1,
                date('Y-m-d H:i:s'),
                0,
                date('Y-m-d H:i:s'),
                0,
                1
            ],
            [
                1,
                null,
                5,
                'theme_options',
                gT('Theme options', 'unescaped'),
                gT('Theme options', 'unescaped'),
                gT('Edit theme options for this survey', 'unescaped'),
                "ri-contrast-drop-fill",
                'remix',
                '',
                'themeOptions/updateSurvey',
                '',
                '',
                '',
                '',
                'surveysettings',
                'update',
                '{"render": {"link": { "pjaxed": true, "data": {"surveyid": ["survey","sid"], "gsid":["survey","gsid"]}}}}',
                '',
                'en-GB',
                1,
                date('Y-m-d H:i:s'),
                0,
                date('Y-m-d H:i:s'),
                0,
                0
            ],
            [
                1,
                null,
                6,
                'presentation',
                gT('Presentation & navigation settings', 'unescaped'),
                gT('Presentation', 'unescaped'),
                gT('Edit presentation and navigation settings', 'unescaped'),
                "ri-slideshow-line",
                'remix',
                '',
                '',
                'updatesurveylocalesettings',
                'editLocalSettings_main_view',
                '/admin/survey/subview/accordion/_presentation_panel',
                '',
                'surveylocale',
                'read',
                null,
                'tabPresentationNavigation',
                'en-GB',
                1,
                date('Y-m-d H:i:s'),
                0,
                date('Y-m-d H:i:s'),
                0,
                0
            ],
            [
                1,
                null,
                7,
                'tokens',
                gT('Survey participant settings', 'unescaped'),
                gT('Participant settings', 'unescaped'),
                gT('Set additional options for survey participants', 'unescaped'),
                "ri-body-scan-fill",
                'remix',
                '',
                '',
                'updatesurveylocalesettings',
                'editLocalSettings_main_view',
                '/admin/survey/subview/accordion/_tokens_panel',
                '',
                'surveylocale',
                'read',
                null,
                'tabTokens',
                'en-GB',
                1,
                date('Y-m-d H:i:s'),
                0,
                date('Y-m-d H:i:s'),
                0,
                0
            ],
            [
                1,
                null,
                8,
                'notification',
                gT('Notification and data management settings', 'unescaped'),
                gT('Notifications & data', 'unescaped'),
                gT('Edit settings for notification and data management', 'unescaped'),
                "ri-notification-line",
                'remix',
                '',
                '',
                'updatesurveylocalesettings',
                'editLocalSettings_main_view',
                '/admin/survey/subview/accordion/_notification_panel',
                '',
                'surveylocale',
                'read',
                null,
                'tabNotificationDataManagement',
                'en-GB',
                1,
                date('Y-m-d H:i:s'),
                0,
                date('Y-m-d H:i:s'),
                0,
                0
            ],
            [
                1,
                null,
                9,
                'publication',
                gT('Publication & access control settings', 'unescaped'),
                gT('Publication & access', 'unescaped'),
                gT('Edit settings for publication and access control', 'unescaped'),
                "ri-key-line",
                'remix',
                '',
                '',
                'updatesurveylocalesettings',
                'editLocalSettings_main_view',
                '/admin/survey/subview/accordion/_publication_panel',
                '',
                'surveylocale',
                'read',
                null,
                'tabPublicationAccess',
                'en-GB',
                1,
                date('Y-m-d H:i:s'),
                0,
                date('Y-m-d H:i:s'),
                0,
                0
            ],
            [
                1,
                null,
                10,
                'surveypermissions',
                gT('Edit survey permissions', 'unescaped'),
                gT('Survey permissions', 'unescaped'),
                gT('Edit permissions for this survey', 'unescaped'),
                "ri-lock-password-line",
                'remix',
                '',
                'surveyPermissions/index',
                '',
                '',
                '',
                '',
                'surveysecurity',
                'read',
                '{"render": { "link": {"data": {"surveyid": ["survey","sid"]}}}}',
                '',
                'en-GB',
                1,
                date('Y-m-d H:i:s'),
                0,
                date('Y-m-d H:i:s'),
                0,
                0
            ],
            [
                2,
                null,
                1,
                'listQuestions',
                gT('Overview questions & groups', 'unescaped'),
                gT('Overview questions & groups', 'unescaped'),
                gT('Overview of questions and groups where you can add, edit and reorder them', 'unescaped'),
                'ri-swap-line',
                'remix',
                '',
                'questionAdministration/listQuestions',
                '',
                '',
                '',
                '',
                'surveycontent',
                'read',
                '{"render": { "link": {"data": {"surveyid": ["survey","sid"]}}}}',
                '',
                'en-GB',
                1,
                date('Y-m-d H:i:s'),
                0,
                date('Y-m-d H:i:s'),
                0,
                1
            ],
            [
                2,
                null,
                4,
                'participants',
                gT('Survey participants', 'unescaped'),
                gT('Participants', 'unescaped'),
                gT('Go to survey participant and token settings', 'unescaped'),
                'ri-contacts-line',
                'remix',
                '',
                'admin/tokens/sa/index/',
                '',
                '',
                '',
                '',
                'tokens',
                'read',
                '{"render": { "link": {"data": {"surveyid": ["survey","sid"]}}}}',
                '',
                'en-GB',
                1,
                date('Y-m-d H:i:s'),
                0,
                date('Y-m-d H:i:s'),
                0,
                1
            ],
            [
                2,
                null,
                5,
                'emailtemplates',
                gT('Email templates', 'unescaped'),
                gT('Email templates', 'unescaped'),
                gT('Edit the templates for invitation, reminder and registration emails', 'unescaped'),
                'ri-mail-line',
                'remix',
                '',
                'admin/emailtemplates/sa/index/',
                '',
                '',
                '',
                '',
                'surveylocale',
                'read',
                '{"render": { "link": {"data": {"surveyid": ["survey","sid"]}}}}',
                '',
                'en-GB',
                1,
                date('Y-m-d H:i:s'),
                0,
                date('Y-m-d H:i:s'),
                0,
                0
            ],
            [
                2,
                null,
                6,
                'failedemail',
                gT('Failed email notifications', 'unescaped'),
                gT('Failed email notifications', 'unescaped'),
                gT('View and resend failed email notifications', 'unescaped'),
                'ri-mail-close-line',
                'remix',
                '',
                'failedEmail/index/',
                '',
                '',
                '',
                '',
                'surveylocale',
                'read',
                '{"render": { "link": {"data": {"surveyid": ["survey","sid"]}}}}',
                '',
                'en-GB',
                1,
                date('Y-m-d H:i:s'),
                0,
                date('Y-m-d H:i:s'),
                0,
                0
            ],
            [
                2,
                null,
                7,
                'quotas',
                gT('Edit quotas', 'unescaped'),
                gT('Quotas', 'unescaped'),
                gT('Edit quotas for this survey.', 'unescaped'),
                'ri-percent-line',
                'remix',
                '',
                'quotas/index/',
                '',
                '',
                '',
                '',
                'quotas',
                'read',
                '{"render": { "link": {"data": {"surveyid": ["survey","sid"]}}}}',
                '',
                'en-GB',
                1,
                date('Y-m-d H:i:s'),
                0,
                date('Y-m-d H:i:s'),
                0,
                0
            ],
            [
                2,
                null,
                8,
                'assessments',
                gT('Edit assessments', 'unescaped')
                ,gT('Assessments', 'unescaped'),
                gT('Edit and look at the assessements for this survey.', 'unescaped'),
                'ri-award-line',
                'remix',
                '',
                'assessment/index',
                '',
                '',
                '',
                '',
                'assessments',
                'read',
                '{"render": { "link": {"data": {"surveyid": ["survey","sid"]}}}}',
                '',
                'en-GB',
                1,
                date('Y-m-d H:i:s'),
                0,
                date('Y-m-d H:i:s'),
                0,
                0
            ],
            [
                2,
                null,
                9,
                'panelintegration',
                gT('Edit survey panel integration', 'unescaped'),
                gT('Panel integration', 'unescaped'),
                gT('Define panel integrations for your survey', 'unescaped'),
                'ri-plug-line',
                'remix',
                '',
                '',
                'updatesurveylocalesettings',
                'editLocalSettings_main_view',
                '/admin/survey/subview/accordion/_integration_panel',
                '',
                'surveylocale',
                'read',
                '{"render": {"link": { "pjaxed": false}}}',
                'tabPanelIntegration',
                'en-GB',
                1,
                date('Y-m-d H:i:s'),
                0,
                date('Y-m-d H:i:s'),
                0,
                0
            ],
            [
                2,
                null,
                10,
                'responses',
                gT('Responses', 'unescaped'),
                gT('Responses', 'unescaped'),
                gT('Responses', 'unescaped'),
                'ri-file-list-3-line',
                'remix',
                '',
                'responses/browse/',
                '',
                '',
                '',
                '',
                'responses',
                'read',
                '{"render": {"isActive": true, "link": {"data": {"surveyId": ["survey", "sid"]}}}}',
                '',
                'en-GB',
                1,
                date('Y-m-d H:i:s'),
                0,
                date('Y-m-d H:i:s'),
                0,
                1
            ],
            [
                2,
                null,
                11,
                'statistics',
                gT('Statistics', 'unescaped'),
                gT('Statistics', 'unescaped'),
                gT('Statistics', 'unescaped'),
                'ri-bar-chart-fill',
                'remix',
                '',
                'admin/statistics/sa/simpleStatistics/',
                '',
                '',
                '',
                '',
                'statistics',
                'read',
                '{"render": {"isActive": true, "link": {"data": {"surveyid": ["survey", "sid"]}}}}',
                '',
                'en-GB',
                1,
                date('Y-m-d H:i:s'),
                0,
                date('Y-m-d H:i:s'),
                0,
                1
            ],
            [
                2,
                null,
                12,
                'resources',
                gT('Add/edit resources (files/images) for this survey', 'unescaped'),
                gT('Resources', 'unescaped'),
                gT('Add/edit resources (files/images) for this survey', 'unescaped'),
                'ri-folder-line',
                'remix',
                '',
                '',
                'updatesurveylocalesettings',
                'editLocalSettings_main_view',
                '/admin/survey/subview/accordion/_resources_panel',
                '',
                'surveylocale',
                'read',
                '{"render": { "link": {"data": {"surveyid": ["survey","sid"]}}}}',
                'tabResourceManagement',
                'en-GB',
                1,
                date('Y-m-d H:i:s'),
                0,
                date('Y-m-d H:i:s'),
                0,
                0
            ],
            [
                2,
                null,
                13,
                'plugins',
                gT('Plugin settings', 'unescaped'),
                gT('Plugins', 'unescaped'),
                gT('Edit plugin settings', 'unescaped'),
                'ri-plug-fill',
                'remix',
                '',
                '',
                'updatesurveylocalesettings',
                'editLocalSettings_main_view',
                '/admin/survey/subview/accordion/_plugins_panel',
                '',
                'surveysettings',
                'read',
                '{"render": {"link": {"data": {"surveyid": ["survey","sid"]}}}}',
                'pluginTabSurvey',
                'en-GB',
                1,
                date('Y-m-d H:i:s'),
                0,
                date('Y-m-d H:i:s'),
                0,
                0
            ],
            [
                3,
                null,
                3,
                'testSurvey',
                gT('Run survey', 'unescaped'),
                gT('Run survey', 'unescaped'),
                gT('Run survey', 'unescaped'),
                "ri-play-fill",
                'remix',
                '',
                'survey/index/',
                '',
                '',
                '',
                '',
                '',
                '',
                '{"render": {"link": {"external": true, "data": {"sid": ["survey","sid"], "newtest": "Y", "lang": ["survey","language"]}}}}',
                '',
                'en-GB',
                1,
                date('Y-m-d H:i:s'),
                0,
                date('Y-m-d H:i:s'),
                0,
                1
            ],
            [
                3,
                null,
                4,
                'surveyLogicFile',
                gT('Survey logic overview', 'unescaped'),
                gT('Survey logic overview', 'unescaped'),
                gT('Survey logic overview', 'unescaped'),
                'ri-git-branch-fill',
                'remix',
                '',
                'admin/expressions/sa/survey_logic_file/',
                '',
                '',
                '',
                '',
                'surveycontent',
                'read',
                '{"render": { "link": {"data": {"sid": ["survey","sid"]}}}}',
                '',
                'en-GB',
                1,
                date('Y-m-d H:i:s'),
                0,
                date('Y-m-d H:i:s'),
                0,
                1
            ],
            [
                3,
                null,
                5,
                'cpdb',
                gT('Central participant database', 'unescaped'),
                gT('Central participant database', 'unescaped'),
                gT('Central participant database', 'unescaped'),
                'ri-group-fill',
                'remix',
                '',
                'admin/participants/sa/displayParticipants',
                '',
                '',
                '',
                '',
                'tokens',
                'read',
                '{"render": {"link": {}}}',
                '',
                'en-GB',
                1,
                date('Y-m-d H:i:s'),
                0,
                date('Y-m-d H:i:s'),
                0,
                1
            ],
        ];
        $returnArray = [];

        foreach ($basicMenues as $basicMenu) {
            $returnArray[] = array_combine($headerArray, $basicMenu);
        }
        App()->setLanguage($sOldLanguage);
        return $returnArray;
    }

    public static function getTemplateDefaultTexts($mode, $language = 'en')
    {

        $sOldLanguage = App()->language;
        App()->setLanguage($language);
        $returnArray = array(
            'admin_detailed_notification_subject' => gT("Response submission for survey {SURVEYNAME} with results", $mode),
            'admin_detailed_notification' => gT("Hello,\n\nA new response was submitted for your survey '{SURVEYNAME}'.\n\nClick the following link to see the individual response:\n{VIEWRESPONSEURL}\n\nClick the following link to edit the individual response:\n{EDITRESPONSEURL}\n\nView statistics by clicking here:\n{STATISTICSURL}\n\n\nThe following answers were given by the participant:\n{ANSWERTABLE}", $mode),
            'admin_detailed_notification_css' => '<style type="text/css">
            .printouttable {
            margin:1em auto;
            }
            .printouttable th {
            text-align: center;
            }
            .printouttable td {
            border-color: #ddf #ddf #ddf #ddf;
            border-style: solid;
            border-width: 1px;
            padding:0.1em 1em 0.1em 0.5em;
            }

            .printouttable td:first-child {
            font-weight: 700;
            text-align: right;
            padding-right: 5px;
            padding-left: 5px;

            }
            .printouttable .printanswersquestion td{
            background-color:#F7F8FF;
            }

            .printouttable .printanswersquestionhead td{
            text-align: left;
            background-color:#ddf;
            }

            .printouttable .printanswersgroup td{
            text-align: center;
            font-weight:bold;
            padding-top:1em;
            }
            </style>',
            'admin_notification_subject' => gT("Response submission for survey {SURVEYNAME}", $mode),
            'admin_notification' => gT("Hello,\n\nA new response was submitted for your survey '{SURVEYNAME}'.\n\nClick the following link to see the individual response:\n{VIEWRESPONSEURL}\n\nClick the following link to edit the individual response:\n{EDITRESPONSEURL}\n\nView statistics by clicking here:\n{STATISTICSURL}", $mode),
            'confirmation_subject' => gT("Confirmation of your participation in our survey"),
            'confirmation' => gT("Dear {FIRSTNAME},\n\nThis email is to confirm that you have completed the survey titled {SURVEYNAME} and your response has been saved. Thank you for participating.\n\nIf you have any further questions about this email, please contact {ADMINNAME} on {ADMINEMAIL}.\n\nSincerely,\n\n{ADMINNAME}", $mode),
            'invitation_subject' => gT("Invitation to participate in a survey", $mode),
            'invitation' => gT("Dear {FIRSTNAME},\n\nYou have been invited to participate in a survey.\n\nThe survey is titled:\n\"{SURVEYNAME}\"\n\n\"{SURVEYDESCRIPTION}\"\n\nTo participate, please click on the link below.\n\nSincerely,\n\n{ADMINNAME} ({ADMINEMAIL})\n\n----------------------------------------------\nClick here to do the survey:\n{SURVEYURL}", $mode) . "\n\n" . gT("If you do not want to participate in this survey and don't want to receive any more invitations please click the following link:\n{OPTOUTURL}", $mode) . "\n\n" . gT("If you are blocklisted but want to participate in this survey and want to receive invitations please click the following link:\n{OPTINURL}", $mode),
            'reminder_subject' => gT("Reminder to participate in a survey", $mode),
            'reminder' => gT("Dear {FIRSTNAME},\n\nRecently we invited you to participate in a survey.\n\nWe note that you have not yet completed the survey, and wish to remind you that the survey is still available should you wish to take part.\n\nThe survey is titled:\n\"{SURVEYNAME}\"\n\n\"{SURVEYDESCRIPTION}\"\n\nTo participate, please click on the link below.\n\nSincerely,\n\n{ADMINNAME} ({ADMINEMAIL})\n\n----------------------------------------------\nClick here to do the survey:\n{SURVEYURL}", $mode) . "\n\n" . gT("If you do not want to participate in this survey and don't want to receive any more invitations please click the following link:\n{OPTOUTURL}", $mode),
            'registration_subject' => gT("Survey registration confirmation", $mode),
            'registration' => gT("Dear {FIRSTNAME},\n\nYou, or someone using your email address, have registered to participate in an online survey titled {SURVEYNAME}.\n\nTo complete this survey, click on the following URL:\n\n{SURVEYURL}\n\nIf you have any questions about this survey, or if you did not register to participate and believe this email is in error, please contact {ADMINNAME} at {ADMINEMAIL}.", $mode)
            );
            App()->setLanguage($sOldLanguage);
        return $returnArray;
    }

    public static function getSurveyMenuData()
    {
        $headerArray = [
            'id',
            'parent_id',
            'survey_id',
            'user_id',
            'ordering',
            'level',
            'name',
            'title',
            'position',
            'description',
            'active',
            'changed_at',
            'changed_by',
            'created_at',
            'created_by',
            'showincollapse'
        ];
        $sOldLanguage = App()->language;
        App()->setLanguage('en');
        $returnArray = [];
        $returnArray[] = array_combine($headerArray, [1,null,null,null,1,0,'settings',gT('Survey settings'),'side',gT('Survey settings'),1, date('Y-m-d H:i:s'),0,date('Y-m-d H:i:s'),0,1]);
        $returnArray[] = array_combine($headerArray, [2,null,null,null,2,0,'mainmenu',gT('Survey menu'),'side',gT('Main survey menu'),1, date('Y-m-d H:i:s'),0,date('Y-m-d H:i:s'),0,1]);
        $returnArray[] = array_combine($headerArray, [3,null,null,null,3,0,'quickmenu',gT('Quick menu'),'collapsed',gT('Quick menu'),1, date('Y-m-d H:i:s'),0,date('Y-m-d H:i:s'),0,0]);
        App()->setLanguage($sOldLanguage);

        return $returnArray;
    }

    public static function getBoxesData()
    {
        $sOldLanguage = App()->language;
        App()->setLanguage('en');
        $returnArray = [];

        $returnArray[] = [
            'position'   => '1',
            'url'        => 'dashboard/view',
            'title'      => gT('Dashboard'),
            'ico'        => 'ri-function-fill',
            'desc'       => gT('View dashboard'),
            'page'       => 'welcome',
            'usergroup'  => '-1',
            'buttontext' => gT('View dashboard')
        ];
        $returnArray[] = [
            'position'   => '2',
            'url'        => 'admin/globalsettings',
            'title'      => gT('Global settings'),
            'ico'        => 'ri-settings-3-fill',
            'desc'       => gT('Edit global settings'),
            'page'       => 'welcome',
            'usergroup'  => '-2',
            'buttontext' => gT('View global settings')
        ];
        $returnArray[] = [
            'position'   => '3',
            'url'        => 'themeOptions',
            'title'      => gT('Themes'),
            'ico'        => 'ri-paint-fill',
            'desc'       => gT('The themes functionality allows you to edit survey-, admin- or question themes.'),
            'page'       => 'welcome',
            'usergroup'  => '-2',
            'buttontext' => gT('Edit themes')
        ];
        $returnArray[] = [
            'position'   => '4',
            'url'        => 'userManagement/index',
            'title'      => gT('Manage administrators'),
            'ico'        => 'ri-group-line',
            'desc'       => gT('The user management allows you to add additional users to your survey administration.'),
            'page'       => 'welcome',
            'usergroup'  => '-2',
            'buttontext' => gT('Manage administrators')
        ];
        $returnArray[] = [
            'position'   => '5',
            'url'        => 'admin/pluginmanager/sa/index',
            'title'      => gT('Plugins'),
            'ico'        => 'ri-plug-fill',
            'desc'       => gT('Plugins can be used to add custom features'),
            'page'       => 'welcome',
            'usergroup'  => '-2',
            'buttontext' => gT('Manage plugins')
        ];

        App()->setLanguage($sOldLanguage);
        return $returnArray;
    }

    /**
     * Returns Template Configuration Data as Array.
     *
     * @return array
     */
    public static function getTemplateConfigurationData()
    {
        $returnArray = [];

        $returnArray[] = [
            'template_name'     =>  'vanilla',
            'sid'               =>  null,
            'gsid'              =>  null,
            'uid'               =>  null,
            'files_css'         => '{"add":["css/base.css","css/theme.css","css/noTablesOnMobile.css","css/custom.css"]}',
            'files_js'          =>  '{"add":["scripts/theme.js","scripts/ajaxify.js","scripts/custom.js"]}',
            'files_print_css'   => '{"add":["css/print_theme.css"]}',
            'options'           => '{"animatebody":"off", "fixnumauto":"enable","brandlogo":"on","container":"on", "hideprivacyinfo": "off", "brandlogofile":"themes/survey/vanilla/files/logo.png","font":"noto", "showpopups":"1", "showclearall":"off", "questionhelptextposition":"top"}',
            'cssframework_name' => 'bootstrap',
            'cssframework_css'  => '{}',
            'cssframework_js'   => '',
            'packages_to_load'  => '{"add":["pjax","font-noto","moment"]}',
            'packages_ltr'      => null,
            'packages_rtl'      => null
        ];
        $returnArray[] = [
            'template_name'     =>  'fruity',
            'sid'               =>  null,
            'gsid'              =>  null,
            'uid'               =>  null,
            'files_css'         => '{"add":["css/ajaxify.css","css/animate.css","css/variations/sea_green.css","css/theme.css","css/custom.css"]}',
            'files_js'          => '{"add":["scripts/theme.js","scripts/ajaxify.js","scripts/custom.js"]}',
            'files_print_css'   => '{"add":["css/print_theme.css"]}',
            'options'           => '{"fixnumauto":"enable","brandlogo":"on","brandlogofile":"themes/survey/fruity/files/logo.png","container":"on","backgroundimage":"off","backgroundimagefile":null,"animatebody":"off","bodyanimation":"fadeInRight","bodyanimationduration":"500","animatequestion":"off","questionanimation":"flipInX","questionanimationduration":"500","animatealert":"off","alertanimation":"shake","alertanimationduration":"500","font":"noto","bodybackgroundcolor":"#ffffff","fontcolor":"#444444","questionbackgroundcolor":"#ffffff","questionborder":"on","questioncontainershadow":"on","checkicon":"f00c","animatecheckbox":"on","checkboxanimation":"rubberBand","checkboxanimationduration":"500","animateradio":"on","radioanimation":"zoomIn","radioanimationduration":"500","zebrastriping":"off","stickymatrixheaders":"off","greyoutselected":"off","hideprivacyinfo":"off","crosshover":"off","showpopups":"1", "showclearall":"off", "questionhelptextposition":"top","notables":"1"}',
            'cssframework_name' => 'bootstrap',
            'cssframework_css'  => '{}',
            'cssframework_js'   => '',
            'packages_to_load'  => '{"add":["pjax","font-noto","moment"]}',
            'packages_ltr'      => null,
            'packages_rtl'      => null
        ];
        $returnArray[] = [
            'template_name'     =>  'bootswatch',
            'sid'               =>  null,
            'gsid'              =>  null,
            'uid'               =>  null,
            'files_css'         => '{"add":["css/ajaxify.css","css/theme.css","css/custom.css"]}',
            'files_js'          =>  '{"add":["scripts/theme.js","scripts/ajaxify.js","scripts/custom.js"]}',
            'files_print_css'   => '{"add":["css/print_theme.css"]}',
            'options'           => '{"fixnumauto":"enable","brandlogo":"on","container":"on","brandlogofile":"themes/survey/bootswatch/files/logo.png", "showpopups":"1", "showclearall":"off", "hideprivacyinfo": "off", "questionhelptextposition":"top"}',
            'cssframework_name' => 'bootstrap',
            'cssframework_css'  => '{"replace":[["css/bootstrap.css","css/variations/flatly.min.css"]]}',
            'cssframework_js'   => '',
            'packages_to_load'  => '{"add":["pjax","font-noto","moment"]}',
            'packages_ltr'      => null,
            'packages_rtl'      => null
        ];
        //the data here has been taken according to the xml-file themes/survey/fruity_twentythree/config.xml
        $returnArray[] = [
            'template_name'     =>  'fruity_twentythree',
            'sid'               =>  null,
            'gsid'              =>  null,
            'uid'               =>  null,
            'files_css'         => '{"add":["css/variations/theme_apple.css","css/base.css","css/custom.css"], "remove":["survey.css", "template-core.css", "awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css", "awesome-bootstrap-checkbox/awesome-bootstrap-checkbox-rtl.css"]}',
            'files_js'          =>  '{"add":["scripts/theme.js","scripts/custom.js"], "remove":["survey.js", "template-core.js"]}',
            'files_print_css'   => '{"add":["css/print_theme.css"]}',
            'options'           => '{"hideprivacyinfo":"off","showpopups":"1","showclearall":"off","questionhelptextposition":"top","fixnumauto":"enable","backgroundimage":"off","backgroundimagefile":".\/files\/pattern.png","brandlogo":"off","brandlogofile":"image::theme::files\/logo.png","font":"ibm-sans", "bodybackgroundcolor":"#ffffff","fontcolor":"#444444", "questionbackgroundcolor":"#ffffff", "checkicon":"EB7A","cornerradius":"2", "deselectsinglechoice":"off", "cssframework":"apple", "notables":"1"}',
            'cssframework_name' => '',
            'cssframework_css'  => '',
            'cssframework_js'   => '',
            'packages_to_load'  => '{"add":["pjax","moment","font-ibm-sans","font-ibm-serif"]}',
            'packages_ltr'      => null,
            'packages_rtl'      => null
        ];

        return $returnArray;
    }


    public static function getSurveygroupData()
    {

        $returnArray = [
            [
            'name' => 'default',
            'title' => 'Default',
            'template' =>  null,
            'description' => 'Default survey group',
            'sortorder' => 0,
            'owner_id' => 1,
            'parent_id' => null,
            'created' => date('Y-m-d H:i:s'),
            'modified' => date('Y-m-d H:i:s'),
            'created_by' => 1
            ]
        ];

        return $returnArray;
    }


    /**
     * Provides the default set of theme/template metadata used by the application to update database.
     *
     * Each element is an associative array describing a template/theme and includes the following keys:
     * - `name`: internal template identifier
     * - `folder`: template folder name
     * - `title`: human-readable title
     * - `creation_date`: creation timestamp (YYYY-MM-DD HH:MM:SS)
     * - `author`, `author_email`, `author_url`: author metadata
     * - `copyright`: copyright notice
     * - `license`: license information
     * - `version`: template version
     * - `api_version`: compatible API/version marker
     * - `view_folder`: folder for view files
     * - `files_folder`: folder for asset files
     * - `description`: localized or HTML description
     * - `last_update`: last update timestamp or null
     * - `owner_id`: owner user id
     * - `extends`: name of a parent template this one extends (empty if none)
     *
     * @return array[] Array of template metadata records.
     */
    public static function getTemplatesData()
    {
        $returnArray = [];

        $returnArray[] = [
            'name'          => 'vanilla',
            'folder'        => 'vanilla',
            'title'         => 'Bootstrap Vanilla',
            'creation_date' => date('Y-m-d H:i:s'),
            'author'        => 'LimeSurvey GmbH',
            'author_email'  => 'info@limesurvey.org',
            'author_url'    => 'https://www.limesurvey.org/',
            'copyright'     => 'Copyright (C) 2007-2026 The LimeSurvey Project Team\\r\\nAll rights reserved.',
            'license'       => 'License: GNU/GPL License v2 or later, see LICENSE.php\\r\\n\\r\\nLimeSurvey is free software. This version may have been modified pursuant to the GNU General Public License, and as distributed it includes or is derivative of works licensed under the GNU General Public License or other free or open source software licenses. See COPYRIGHT.php for copyright notices and details.',
            'version'       => '3.0',
            'api_version'   => '3.0',
            'view_folder'   => 'views',
            'files_folder'  => 'files',
            'description'   => "A clean and simple base that can be used by developers to create their own Bootstrap based theme.",
            'last_update'   => null,
            'owner_id'      => 1,
            'extends'       => '',
        ];
        $returnArray[] = [
            'name'          => 'fruity',
            'folder'        => 'fruity',
            'title'         => 'Fruity',
            'creation_date' => date('Y-m-d H:i:s'),
            'author'        => 'LimeSurvey GmbH',
            'author_email'  => 'info@limesurvey.org',
            'author_url'    => 'https://www.limesurvey.org/',
            'copyright'     => 'Copyright (C) 2007-2026 The LimeSurvey Project Team\\r\\nAll rights reserved.',
            'license'       => 'License: GNU/GPL License v2 or later, see LICENSE.php\\r\\n\\r\\nLimeSurvey is free software. This version may have been modified pursuant to the GNU General Public License, and as distributed it includes or is derivative of works licensed under the GNU General Public License or other free or open source software licenses. See COPYRIGHT.php for copyright notices and details.',
            'version'       => '3.0',
            'api_version'   => '3.0',
            'view_folder'   => 'views',
            'files_folder'  => 'files',
            'description'   => "A fruity theme for a flexible use. This theme offers monochromes variations and many options for easy customizations.",
            'last_update'   => null,
            'owner_id'      => 1,
            'extends'       => 'vanilla',
        ];
        $returnArray[] = [
            'name'          => 'bootswatch',
            'folder'        => 'bootswatch',
            'title'         => 'Bootswatch',
            'creation_date' => date('Y-m-d H:i:s'),
            'author'        => 'LimeSurvey GmbH',
            'author_email'  => 'info@limesurvey.org',
            'author_url'    => 'https://www.limesurvey.org/',
            'copyright'     => 'Copyright (C) 2007-2026 The LimeSurvey Project Team\\r\\nAll rights reserved.',
            'license'       => 'License: GNU/GPL License v2 or later, see LICENSE.php\\r\\n\\r\\nLimeSurvey is free software. This version may have been modified pursuant to the GNU General Public License, and as distributed it includes or is derivative of works licensed under the GNU General Public License or other free or open source software licenses. See COPYRIGHT.php for copyright notices and details.',
            'version'       => '3.0',
            'api_version'   => '3.0',
            'view_folder'   => 'views',
            'files_folder'  => 'files',
            'description'   => '{{gT("Based on BootsWatch Themes:")}}<br><a href=\'https://bootswatch.com/3/\' target=\'_blank\' rel=\'external\' title=\'{{gT("Visit Bootswatch page in a new window.")}}\'>{{gT("Visit Bootswatch page")}} <i class=\'ri-external-link-line\'></i><span class=\'visually-hidden\'>{{gT("(Opens in a new window)")}}</span></a>',
            'last_update'   => null,
            'owner_id'      => 1,
            'extends'       => 'vanilla',
        ];
        $returnArray[] = [
            'name'          => 'fruity_twentythree',
            'folder'        => 'fruity_twentythree',
            'title'         => 'Fruity TwentyThree',
            'creation_date' => date('Y-m-d H:i:s'),
            'author'        => 'LimeSurvey GmbH',
            'author_email'  => 'info@limesurvey.org',
            'author_url'    => 'https://www.limesurvey.org/',
            'copyright'     => 'Copyright (C) 2005 - 2023 LimeSurvey Gmbh, Inc. All rights reserved.',
            'license'       => 'License: GNU/GPL License v2 or later, see LICENSE.php\\r\\n\\r\\nLimeSurvey is free software. This version may have been modified pursuant to the GNU General Public License, and as distributed it includes or is derivative of works licensed under the GNU General Public License or other free or open source software licenses. See COPYRIGHT.php for copyright notices and details.',
            'version'       => '1.0.0',
            'api_version'   => '3.0',
            'view_folder'   => 'views',
            'files_folder'  => 'files',
            'description'   => "Our default theme for a fruity and flexible use. This theme offers single color variations",
            'last_update'   => null,
            'owner_id'      => 1,
            'extends'       => '',
        ];

        return $returnArray;
    }

    /**
     * Get data for plugins installed by default.
     * Also install all core plugins, but set to inactive.
     *
     * @return array
     */
    public static function getDefaultPluginsData()
    {
        /**
         * @param string $name Name of plugin
         * @param int $active
         * @return array
         */
        $addRow = function ($name, $active = 0, $version = '1.0.0', $priority = 1) {
            return [
                'id' => null,
                'name'               => $name,
                'plugin_type'        => 'core',
                'active'             => $active,
                'version'            => $version,
                'load_error'         => 0,
                'load_error_message' => null,
                'priority'           => $priority,
            ];
        };

        return [
            $addRow('UpdateCheck', 1),
            $addRow('PasswordRequirement', 1),
            $addRow('ComfortUpdateChecker', 1),
            $addRow('Authdb', 1),
            $addRow('ReactEditor', 1, '1.0.0', 0),
            // Inactive plugins below.
            $addRow('AuthLDAP'),
            $addRow('AuditLog'),
            $addRow('Authwebserver'),
            $addRow('ExportR', 1),
            $addRow('ExportSTATAxml', 1),
            $addRow('ExportSPSSsav', 1),
            $addRow('oldUrlCompat'),
            $addRow('expressionQuestionHelp', 0, '1.0.1', 0),
            $addRow('expressionQuestionForAll'),
            $addRow('expressionFixedDbVar'),
            $addRow('customToken', 0, '1.0.1'),
            $addRow('mailSenderToFrom'),
            $addRow('TwoFactorAdminLogin', 0, '1.2.5'),
        ];
    }

    public static function getDefaultUserSettings()
    {
        return [
            ['stg_name' => 'editorPreset', 'stg_value' => 'wysiwyg'],
            ['stg_name' => 'showScriptEdit', 'stg_value' => '1'],
            ['stg_name' => 'noViewMode', 'stg_value' => '0'],
            ['stg_name' => 'answeroptionprefix', 'stg_value' => 'AO'],
            ['stg_name' => 'subquestionprefix', 'stg_value' => 'SQ'],
            ['stg_name' => 'lock_organizer', 'stg_value' => '0'],
            ['stg_name' => 'breadcrumbMode', 'stg_value' => 'default'],
        ];
    }

    public static function getBaseLabelSets($language = 'en')
    {
        $sOldLanguage = App()->language;
        Yii::app()->setLanguage($language);

        $returnArray = [
            'likert-5-point' => [
                '1' => gT("Strongly disagree"),
                '2' => gT('Disagree'),
                '3' => gT('Neither agree nor disagree'),
                '4' => gT('Agree'),
                '5' => gT('Strongly agree'),
            ],
            'likert-4-point' => [
                '1' => gT('Strongly disagree'),
                '2' => gT('Disagree'),
                '3' => gT('Agree'),
                '4' => gT('Strongly agree'),
            ],
        ];

        Yii::app()->setLanguage($sOldLanguage);

        return $returnArray;
    }

    public static function getBaseQuestionThemeEntries()
    {
        $aBaseQuestionThemes = [
            array(
                "name" => "5pointchoice",
                "visible" => "Y",
                "xml_path" => "application/views/survey/questions/answer/5pointchoice",
                "image_path" => "/assets/images/screenshots/5.png",
                "title" => "5 point choice",
                "creation_date" => "2018-09-08 00:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "5 point choice question type configuration",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "5",
                "core_theme" => 1,
                "extends" => "",
                "group" => "Single choice questions",
                "settings" => "{\"subquestions\":\"0\",\"answerscales\":\"0\",\"hasdefaultvalues\":\"0\",\"assessable\":\"0\",\"class\":\"choice-5-pt-radio\"}",
            ),
            array(
                "name" => "arrays/10point",
                "visible" => "Y",
                "xml_path" => "application/views/survey/questions/answer/arrays/10point",
                "image_path" => "/assets/images/screenshots/B.png",
                "title" => "Array (10 point choice)",
                "creation_date" => "2018-09-08 00:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "Array (10 point choice) question type configuration",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "B",
                "core_theme" => 1,
                "extends" => "",
                "group" => "Arrays",
                "settings" => "{\"subquestions\":\"1\",\"answerscales\":\"0\",\"hasdefaultvalues\":\"0\",\"assessable\":\"1\",\"class\":\"array-10-pt\"}",
            ),
            array(
                "name" => "arrays/5point",
                "visible" => "Y",
                "xml_path" => "application/views/survey/questions/answer/arrays/5point",
                "image_path" => "/assets/images/screenshots/A.png",
                "title" => "Array (5 point choice)",
                "creation_date" => "2018-09-08 00:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "Array (5 point choice) question type configuration",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "A",
                "core_theme" => 1,
                "extends" => "",
                "group" => "Arrays",
                "settings" => "{\"subquestions\":\"1\",\"answerscales\":\"0\",\"hasdefaultvalues\":\"0\",\"assessable\":\"1\",\"class\":\"array-5-pt\"}",
            ),
            array(
                "name" => "arrays/array",
                "visible" => "Y",
                "xml_path" => "application/views/survey/questions/answer/arrays/array",
                "image_path" => "/assets/images/screenshots/F.png",
                "title" => "Array",
                "creation_date" => "2018-09-08 00:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "Array question type configuration",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "F",
                "core_theme" => 1,
                "extends" => "",
                "group" => "Arrays",
                "settings" => "{\"subquestions\":\"1\",\"answerscales\":\"1\",\"hasdefaultvalues\":\"0\",\"assessable\":\"1\",\"class\":\"array-flexible-row\"}",
            ),
            array(
                "name" => "arrays/column",
                "visible" => "Y",
                "xml_path" => "application/views/survey/questions/answer/arrays/column",
                "image_path" => "/assets/images/screenshots/H.png",
                "title" => "Array by column",
                "creation_date" => "2018-09-08 00:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "Array by column question type configuration",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "H",
                "core_theme" => 1,
                "extends" => "",
                "group" => "Arrays",
                "settings" => "{\"subquestions\":\"1\",\"answerscales\":\"1\",\"hasdefaultvalues\":\"0\",\"assessable\":\"1\",\"class\":\"array-flexible-column\"}",
            ),
            array(
                "name" => "arrays/dualscale",
                "visible" => "Y",
                "xml_path" => "application/views/survey/questions/answer/arrays/dualscale",
                "image_path" => "/assets/images/screenshots/1.png",
                "title" => "Array dual scale",
                "creation_date" => "2018-09-08 00:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "Array dual scale question type configuration",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "1",
                "core_theme" => 1,
                "extends" => "",
                "group" => "Arrays",
                "settings" => "{\"subquestions\":\"1\",\"answerscales\":\"2\",\"hasdefaultvalues\":\"0\",\"assessable\":\"1\",\"class\":\"array-flexible-dual-scale\"}",
            ),
            array(
                "name" => "arrays/increasesamedecrease",
                "visible" => "Y",
                "xml_path" => "application/views/survey/questions/answer/arrays/increasesamedecrease",
                "image_path" => "/assets/images/screenshots/E.png",
                "title" => "Array (Increase/Same/Decrease)",
                "creation_date" => "2018-09-08 00:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "Array (Increase/Same/Decrease) question type configuration",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "E",
                "core_theme" => 1,
                "extends" => "",
                "group" => "Arrays",
                "settings" => "{\"subquestions\":\"1\",\"answerscales\":\"0\",\"hasdefaultvalues\":\"0\",\"assessable\":\"1\",\"class\":\"array-increase-same-decrease\"}",
            ),
            array(
                "name" => "arrays/multiflexi",
                "visible" => "Y",
                "xml_path" => "application/views/survey/questions/answer/arrays/multiflexi",
                "image_path" => "/assets/images/screenshots/COLON.png",
                "title" => "Array (Numbers)",
                "creation_date" => "2018-09-08 00:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "Array (Numbers) question type configuration",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => ":",
                "core_theme" => 1,
                "extends" => "",
                "group" => "Arrays",
                "settings" => "{\"subquestions\":\"2\",\"answerscales\":\"0\",\"hasdefaultvalues\":\"0\",\"assessable\":\"1\",\"class\":\"array-multi-flexi\"}",
            ),
            array(
                "name" => "arrays/texts",
                "visible" => "Y",
                "xml_path" => "application/views/survey/questions/answer/arrays/texts",
                "image_path" => "/assets/images/screenshots/;.png",
                "title" => "Array (Texts)",
                "creation_date" => "2018-09-08 00:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "Array (Texts) question type configuration",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => ";",
                "core_theme" => 1,
                "extends" => "",
                "group" => "Arrays",
                "settings" => "{\"subquestions\":\"2\",\"answerscales\":\"0\",\"hasdefaultvalues\":\"0\",\"assessable\":\"0\",\"class\":\"array-multi-flexi-text\"}",
            ),
            array(
                "name" => "arrays/yesnouncertain",
                "visible" => "Y",
                "xml_path" => "application/views/survey/questions/answer/arrays/yesnouncertain",
                "image_path" => "/assets/images/screenshots/C.png",
                "title" => "Array (Yes/Uncertain/No)",
                "creation_date" => "2018-09-08 00:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "Array (Yes/Uncertain/No) question type configuration",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "C",
                "core_theme" => 1,
                "extends" => "",
                "group" => "Arrays",
                "settings" => "{\"subquestions\":\"1\",\"answerscales\":\"0\",\"hasdefaultvalues\":\"0\",\"assessable\":\"1\",\"class\":\"array-yes-uncertain-no\"}",
            ),
            array(
                "name" => "boilerplate",
                "visible" => "Y",
                "xml_path" => "application/views/survey/questions/answer/boilerplate",
                "image_path" => "/assets/images/screenshots/X.png",
                "title" => "Text display",
                "creation_date" => "2018-09-08 00:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "Text display question type configuration",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "X",
                "core_theme" => 1,
                "extends" => "",
                "group" => "Mask questions",
                "settings" => "{\"subquestions\":\"0\",\"answerscales\":\"0\",\"hasdefaultvalues\":\"0\",\"assessable\":\"0\",\"class\":\"boilerplate\"}",
            ),
            array(
                "name" => "date",
                "visible" => "Y",
                "xml_path" => "application/views/survey/questions/answer/date",
                "image_path" => "/assets/images/screenshots/D.png",
                "title" => "Date/Time",
                "creation_date" => "2018-09-08 00:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "Date/Time question type configuration",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "D",
                "core_theme" => 1,
                "extends" => "",
                "group" => "Mask questions",
                "settings" => "{\"subquestions\":\"0\",\"answerscales\":\"0\",\"hasdefaultvalues\":\"1\",\"assessable\":\"0\",\"class\":\"date\"}",
            ),
            array(
                "name" => "equation",
                "visible" => "Y",
                "xml_path" => "application/views/survey/questions/answer/equation",
                "image_path" => "/assets/images/screenshots/EQUATION.png",
                "title" => "Equation",
                "creation_date" => "2018-09-08 00:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "Equation question type configuration",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "*",
                "core_theme" => 1,
                "extends" => "",
                "group" => "Mask questions",
                "settings" => "{\"subquestions\":\"0\",\"answerscales\":\"0\",\"hasdefaultvalues\":\"0\",\"assessable\":\"0\",\"class\":\"equation\"}",
            ),
            array(
                "name" => "file_upload",
                "visible" => "Y",
                "xml_path" => "application/views/survey/questions/answer/file_upload",
                "image_path" => "/assets/images/screenshots/PIPE.png",
                "title" => "File upload",
                "creation_date" => "2018-09-08 00:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "File upload question type configuration",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "|",
                "core_theme" => 1,
                "extends" => "",
                "group" => "Mask questions",
                "settings" => "{\"subquestions\":\"0\",\"answerscales\":\"0\",\"hasdefaultvalues\":\"0\",\"assessable\":\"0\",\"class\":\"upload-files\"}",
            ),
            array(
                "name" => "gender",
                "visible" => "Y",
                "xml_path" => "application/views/survey/questions/answer/gender",
                "image_path" => "/assets/images/screenshots/G.png",
                "title" => "Gender",
                "creation_date" => "2018-09-08 00:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "Gender question type configuration",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "G",
                "core_theme" => 1,
                "extends" => "",
                "group" => "Mask questions",
                "settings" => "{\"subquestions\":\"0\",\"answerscales\":\"0\",\"hasdefaultvalues\":\"0\",\"assessable\":\"0\",\"class\":\"gender\"}",
            ),
            array(
                "name" => "hugefreetext",
                "visible" => "Y",
                "xml_path" => "application/views/survey/questions/answer/hugefreetext",
                "image_path" => "/assets/images/screenshots/U.png",
                "title" => "Huge free text",
                "creation_date" => "1970-01-01 01:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "Huge free text question type configuration",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "U",
                "core_theme" => 1,
                "extends" => "",
                "group" => "Text questions",
                "settings" => "{\"subquestions\":\"0\",\"answerscales\":\"0\",\"hasdefaultvalues\":\"1\",\"assessable\":\"0\",\"class\":\"text-huge\"}",
            ),
            array(
                "name" => "language",
                "visible" => "Y",
                "xml_path" => "application/views/survey/questions/answer/language",
                "image_path" => "/assets/images/screenshots/I.png",
                "title" => "Language switch",
                "creation_date" => "2018-09-08 00:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "Language switch question type configuration",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "I",
                "core_theme" => 1,
                "extends" => "",
                "group" => "Mask questions",
                "settings" => "{\"subquestions\":\"0\",\"answerscales\":\"0\",\"hasdefaultvalues\":\"0\",\"assessable\":\"0\",\"class\":\"language\"}",
            ),
            array(
                "name" => "listradio",
                "visible" => "Y",
                "xml_path" => "application/views/survey/questions/answer/listradio",
                "image_path" => "/assets/images/screenshots/L.png",
                "title" => "List (Radio)",
                "creation_date" => "2018-09-08 00:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "List (radio) question type configuration",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "L",
                "core_theme" => 1,
                "extends" => "",
                "group" => "Single choice questions",
                "settings" => "{\"subquestions\":\"0\",\"answerscales\":\"1\",\"hasdefaultvalues\":\"1\",\"assessable\":\"1\",\"class\":\"list-radio\"}",
            ),
            array(
                "name" => "list_dropdown",
                "visible" => "Y",
                "xml_path" => "application/views/survey/questions/answer/list_dropdown",
                "image_path" => "/assets/images/screenshots/!.png",
                "title" => "List (Dropdown)",
                "creation_date" => "2018-09-08 00:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "List (dropdown) question type configuration",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "!",
                "core_theme" => 1,
                "extends" => "",
                "group" => "Single choice questions",
                "settings" => "{\"subquestions\":\"0\",\"answerscales\":\"1\",\"hasdefaultvalues\":\"1\",\"assessable\":\"1\",\"class\":\"list-dropdown\"}",
            ),
            array(
                "name" => "list_with_comment",
                "visible" => "Y",
                "xml_path" => "application/views/survey/questions/answer/list_with_comment",
                "image_path" => "/assets/images/screenshots/O.png",
                "title" => "List with comment",
                "creation_date" => "2018-09-08 00:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "List with comment question type configuration",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "O",
                "core_theme" => 1,
                "extends" => "",
                "group" => "Single choice questions",
                "settings" => "{\"subquestions\":\"0\",\"answerscales\":\"1\",\"hasdefaultvalues\":\"1\",\"assessable\":\"1\",\"class\":\"list-with-comment\"}",
            ),
            array(
                "name" => "longfreetext",
                "visible" => "Y",
                "xml_path" => "application/views/survey/questions/answer/longfreetext",
                "image_path" => "/assets/images/screenshots/T.png",
                "title" => "Long free text",
                "creation_date" => "2018-09-08 00:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "Long free text question type configuration",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "T",
                "core_theme" => 1,
                "extends" => "",
                "group" => "Text questions",
                "settings" => "{\"subquestions\":\"0\",\"answerscales\":\"0\",\"hasdefaultvalues\":\"1\",\"assessable\":\"0\",\"class\":\"text-long\"}",
            ),
            array(
                "name" => "multiplechoice",
                "visible" => "Y",
                "xml_path" => "application/views/survey/questions/answer/multiplechoice",
                "image_path" => "/assets/images/screenshots/M.png",
                "title" => "Multiple choice",
                "creation_date" => "2018-09-08 00:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "Multiple choice question type configuration",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "M",
                "core_theme" => 1,
                "extends" => "",
                "group" => "Multiple choice questions",
                "settings" => "{\"subquestions\":\"1\",\"answerscales\":\"0\",\"hasdefaultvalues\":\"1\",\"assessable\":\"1\",\"class\":\"multiple-opt\"}",
            ),
            array(
                "name" => "multiplechoice_with_comments",
                "visible" => "Y",
                "xml_path" => "application/views/survey/questions/answer/multiplechoice_with_comments",
                "image_path" => "/assets/images/screenshots/P.png",
                "title" => "Multiple choice with comments",
                "creation_date" => "2018-09-08 00:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "Multiple choice with comments question type configuration",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "P",
                "core_theme" => 1,
                "extends" => "",
                "group" => "Multiple choice questions",
                "settings" => "{\"subquestions\":\"1\",\"answerscales\":\"0\",\"hasdefaultvalues\":\"1\",\"assessable\":\"1\",\"class\":\"multiple-opt-comments\"}",
            ),
            array(
                "name" => "multiplenumeric",
                "visible" => "Y",
                "xml_path" => "application/views/survey/questions/answer/multiplenumeric",
                "image_path" => "/assets/images/screenshots/K.png",
                "title" => "Multiple numerical input",
                "creation_date" => "2018-09-08 00:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "Multiple numerical input question type configuration",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "K",
                "core_theme" => 1,
                "extends" => "",
                "group" => "Mask questions",
                "settings" => "{\"subquestions\":\"1\",\"answerscales\":\"0\",\"hasdefaultvalues\":\"1\",\"assessable\":\"1\",\"class\":\"numeric-multi\"}",
            ),
            array(
                "name" => "multipleshorttext",
                "visible" => "Y",
                "xml_path" => "application/views/survey/questions/answer/multipleshorttext",
                "image_path" => "/assets/images/screenshots/Q.png",
                "title" => "Multiple short text",
                "creation_date" => "2018-09-08 00:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "Multiple short text question type configuration",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "Q",
                "core_theme" => 1,
                "extends" => "",
                "group" => "Text questions",
                "settings" => "{\"subquestions\":\"1\",\"answerscales\":\"0\",\"hasdefaultvalues\":\"1\",\"assessable\":\"0\",\"class\":\"multiple-short-txt\"}",
            ),
            array(
                "name" => "numerical",
                "visible" => "Y",
                "xml_path" => "application/views/survey/questions/answer/numerical",
                "image_path" => "/assets/images/screenshots/N.png",
                "title" => "Numerical input",
                "creation_date" => "2018-09-08 00:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "Numerical input question type configuration",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "N",
                "core_theme" => 1,
                "extends" => "",
                "group" => "Mask questions",
                "settings" => "{\"subquestions\":\"0\",\"answerscales\":\"0\",\"hasdefaultvalues\":\"1\",\"assessable\":\"0\",\"class\":\"numeric\"}",
            ),
            array(
                "name" => "ranking",
                "visible" => "Y",
                "xml_path" => "application/views/survey/questions/answer/ranking",
                "image_path" => "/assets/images/screenshots/R.png",
                "title" => "Ranking",
                "creation_date" => "2018-09-08 00:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "Ranking question type configuration",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "R",
                "core_theme" => 1,
                "extends" => "",
                "group" => "Mask questions",
                "settings" => "{\"subquestions\":\"1\",\"answerscales\":\"0\",\"hasdefaultvalues\":\"0\",\"assessable\":\"1\",\"class\":\"ranking\"}",
            ),
            array(
                "name" => "shortfreetext",
                "visible" => "Y",
                "xml_path" => "application/views/survey/questions/answer/shortfreetext",
                "image_path" => "/assets/images/screenshots/S.png",
                "title" => "Short free text",
                "creation_date" => "2018-09-08 00:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "Short free text question type configuration",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "S",
                "core_theme" => 1,
                "extends" => "",
                "group" => "Text questions",
                "settings" => "{\"subquestions\":\"0\",\"answerscales\":\"0\",\"hasdefaultvalues\":\"1\",\"assessable\":\"0\",\"class\":\"text-short\"}",
            ),
            array(
                "name" => "yesno",
                "visible" => "Y",
                "xml_path" => "application/views/survey/questions/answer/yesno",
                "image_path" => "/assets/images/screenshots/Y.png",
                "title" => "Yes/No",
                "creation_date" => "2018-09-08 00:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "Yes/No question type configuration",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "Y",
                "core_theme" => 1,
                "extends" => "",
                "group" => "Mask questions",
                "settings" => "{\"subquestions\":\"0\",\"answerscales\":\"0\",\"hasdefaultvalues\":\"1\",\"assessable\":\"0\",\"class\":\"yes-no\"}",
            ),
            array(
                "name" => "bootstrap_dropdown",
                "visible" => "Y",
                "xml_path" => "themes/question/bootstrap_dropdown/survey/questions/answer/list_dropdown",
                "image_path" => "/themes/question/bootstrap_dropdown/survey/questions/answer/list_dropdown/assets/bootstrap_dropdown_list_dropdown.png",
                "title" => "Bootstrap dropdown",
                "creation_date" => "1970-01-01 01:00:00",
                "author" => "Adam Zammit",
                "author_email" => "adam.zammit@acspri.org.au",
                "author_url" => "https://www.acspri.org.au",
                "copyright" => "Copyright (C) 2021 The Australian Consortium for Social and Political Research Incorporated (ACSPRI)",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "Bootstrap dropdown theme",
                "last_update" => "2021-09-29 12:00:00",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "!",
                "core_theme" => 1,
                "extends" => "!",
                "group" => "Single choice questions",
                "settings" => "{\"subquestions\":\"0\",\"answerscales\":\"1\",\"hasdefaultvalues\":\"1\",\"assessable\":\"1\",\"class\":\"list-dropdown\"}",
            ),
            array(
                "name" => "bootstrap_buttons",
                "visible" => "Y",
                "xml_path" => "themes/question/bootstrap_buttons/survey/questions/answer/listradio",
                "image_path" => "/themes/question/bootstrap_buttons/survey/questions/answer/listradio/assets/bootstrap_buttons_listradio.png",
                "title" => "Bootstrap buttons",
                "creation_date" => "1970-01-01 01:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "New implementation of the Bootstrap buttons question theme",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "L",
                "core_theme" => 1,
                "extends" => "L",
                "group" => "Single choice questions",
                "settings" => "{\"subquestions\":\"0\",\"answerscales\":\"1\",\"hasdefaultvalues\":\"1\",\"assessable\":\"1\",\"class\":\"list-radio\"}",
            ),
            array(
                "name" => "bootstrap_buttons_multi",
                "visible" => "Y",
                "xml_path" => "themes/question/bootstrap_buttons_multi/survey/questions/answer/multiplechoice",
                "image_path" => "/themes/question/bootstrap_buttons_multi/survey/questions/answer/multiplechoice/assets/bootstrap_buttons_multiplechoice.png",
                "title" => "Bootstrap buttons",
                "creation_date" => "1970-01-01 01:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2018 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "New implementation of the Bootstrap buttons question theme",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "M",
                "core_theme" => 1,
                "extends" => "M",
                "group" => "Multiple choice questions",
                "settings" => "{\"subquestions\":\"1\",\"answerscales\":\"0\",\"hasdefaultvalues\":\"1\",\"assessable\":\"1\",\"class\":\"multiple-opt\"}",
            ),
            array(
                "name" => "browserdetect",
                "visible" => "Y",
                "xml_path" => "themes/question/browserdetect/survey/questions/answer/shortfreetext",
                "image_path" => "themes/question/browserdetect/survey/questions/answer/shortfreetext/assets/browserdetect.png",
                "title" => "Browser detection",
                "creation_date" => "2017-07-09 00:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2017 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "Browser, Platform and Proxy detection",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "S",
                "core_theme" => 1,
                "extends" => "S",
                "group" => "Text questions",
                "settings" => "{\"subquestions\":\"0\",\"answerscales\":\"0\",\"hasdefaultvalues\":\"1\",\"assessable\":\"0\",\"class\":\"text-short\"}",
            ),
            array(
                "name" => "image_select-listradio",
                "visible" => "Y",
                "xml_path" => "themes/question/image_select-listradio/survey/questions/answer/listradio",
                "image_path" => "themes/question/image_select-listradio/survey/questions/answer/listradio/assets/image_select_listradio.png",
                "title" => "Image select list (Radio)",
                "creation_date" => "1970-01-01 01:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2016 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "List Radio with images.",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "L",
                "core_theme" => 1,
                "extends" => "L",
                "group" => "Single choice questions",
                "settings" => "{\"subquestions\":\"0\",\"answerscales\":\"1\",\"hasdefaultvalues\":\"1\",\"assessable\":\"1\",\"class\":\"list-radio\"}",
            ),
            array(
                "name" => "image_select-multiplechoice",
                "visible" => "Y",
                "xml_path" => "themes/question/image_select-multiplechoice/survey/questions/answer/multiplechoice",
                "image_path" => "themes/question/image_select-multiplechoice/survey/questions/answer/multiplechoice/assets/image_select_multiplechoice.png",
                "title" => "Image select multiple choice",
                "creation_date" => "1970-01-01 01:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2016 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "Multiplechoice with images.",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "M",
                "core_theme" => 1,
                "extends" => "M",
                "group" => "Multiple choice questions",
                "settings" => "{\"subquestions\":\"1\",\"answerscales\":\"0\",\"hasdefaultvalues\":\"1\",\"assessable\":\"1\",\"class\":\"multiple-opt\"}",
            ),
            array(
                "name" => "inputondemand",
                "visible" => "Y",
                "xml_path" => "themes/question/inputondemand/survey/questions/answer/multipleshorttext",
                "image_path" => "themes/question/inputondemand/survey/questions/answer/multipleshorttext/assets/inputondemand.png",
                "title" => "Input on demand",
                "creation_date" => "2019-10-04 00:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2019 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "Hide not needed input fields in multiple shorttext",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "Q",
                "core_theme" => 1,
                "extends" => "Q",
                "group" => "Text questions",
                "settings" => "{\"subquestions\":\"1\",\"answerscales\":\"0\",\"hasdefaultvalues\":\"1\",\"assessable\":\"0\",\"class\":\"multiple-short-txt\"}",
            ),
            array(
                "name" => "ranking_advanced",
                "visible" => "Y",
                "xml_path" => "themes/question/ranking_advanced/survey/questions/answer/ranking",
                "image_path" => "themes/question/ranking_advanced/survey/questions/answer/ranking/assets/advanced_ranking.png",
                "title" => "Ranking advanced",
                "creation_date" => "1970-01-01 01:00:00",
                "author" => "LimeSurvey GmbH",
                "author_email" => "info@limesurvey.org",
                "author_url" => "http://www.limesurvey.org",
                "copyright" => "Copyright (C) 2005 - 2017 LimeSurvey Gmbh, Inc. All rights reserved.",
                "license" => "GNU General Public License version 2 or later",
                "version" => "1.0",
                "api_version" => "1",
                "description" => "New implementation of the ranking question",
                "last_update" => "2019-09-23 15:05:59",
                "owner_id" => 1,
                "theme_type" => "question_theme",
                "question_type" => "R",
                "core_theme" => 1,
                "extends" => "R",
                "group" => "Mask questions",
                "settings" => "{\"subquestions\":\"1\",\"answerscales\":\"0\",\"hasdefaultvalues\":\"0\",\"assessable\":\"1\",\"class\":\"ranking\"}",
            ),
        ];

        return $aBaseQuestionThemes;
    }

    /**
     * All translations that are used in files that can or should not be searched by the translation script.
     * This function has no functionality except for being searchable by the translation script.
     *
     * @return void
     */
    public static function mockTranslateArrayContainer()
    {
        $translationArray = [
            // Survey theme option titles, categories and button labels from themes/survey/*/config.xml attributes
            gT("Survey container"),
            gT("Hide privacy info"),
            gT("Show popups"),
            gT("Popup"),
            gT("On page"),
            gT("Fix automatically numeric value"),
            gT("For expression"),
            gT("Question borders"),
            gT("Question shadow"),
            gT("Zebra-striped questions"),
            gT("Sticky array headers"),
            gT("Dim answered array rows"),
            gT("Cross-hover in matrix questions"),
            gT("Background color"),
            gT("Font color"),
            gT("Question background color"),
            gT("Check icon"),
            gT("Background image"),
            gT("Background image file"),
            gT("Logo"),
            gT("Logo file"),
            gT("Animate body"),
            gT("Body animation"),
            gT("Duration"),
            gT("Animate question"),
            gT("Question animation"),
            gT("Animate alert"),
            gT("Alert animation"),
            gT("Animate checkbox"),
            gT("Animate radio buttons"),
            gT("Radio button animation"),
            gT("Show 'Clear all' button"),
            gT("Wrap tables"),
            gT("Always on"),
            gT("Small screens"),
            gT("Question help text position"),
            gT("Top"),
            gT("Bottom"),
            gT("Deselect single-choice option by click"),
            gT("Corner radius"),
            gT("Theme color"),
            gT("Variations"),
            gT("Colors"),
            gT("Animations"),
            gT("Fonts")
        ];
    }

    /**
     * Email content for registration email (subject and body)
     * Default user administration global configuration settings
     *
     * @return array with user administration default setting
     *                  ['sendadmincreationemail'] set to 1, to indicate that email should be send?
     */
    public static function getDefaultUserAdministrationSettings()
    {
        $default =  [];
        $template = "<p>" . gT("Hello") . " {FULLNAME}, </p>";
        $template .= "<p>" . sprintf(gT("This is an automated email notification that a user has been created for you on the website %s."), "<strong>'{SITENAME}'</strong>") . "</p>";
        $template .= "<p></p><p>" . gT("You can use now the following credentials to log in:") . "</p>";
        $template .= "<p><strong>" . gT("Username") . "</strong>: {USERNAME}</p>";
        //don't send password anymore, just send a link for the new admin to generate their own password
        //$template .= "<p><strong>" . gT("Password") . "</strong>: {PASSWORD}</p>";
        $template .= '<p><a href="{LOGINURL}">' . gT("Click here to set your password") . '</a></p>';
        $template .= "<p>" . sprintf(gT("If you have any questions regarding this mail please do not hesitate to contact the site administrator at %s. Thank you!"), "{SITEADMINEMAIL}") . "</p><p> </p>";
        $default['sendadmincreationemail'] = 1;
        $default['admincreationemailsubject']  = sprintf(gT("User registration at '%s'", "unescaped"), "{SITENAME}");
        $default['admincreationemailtemplate'] = $template;

        return $default;
    }
}
