import {
  AddIcon,
  AlignLeftIcon,
  AlignMiddleIcon,
  AlignRightIcon,
  ArrowDownIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  BrushIcon,
  CheckIcon,
  ClipBoardIcon,
  ClockIcon,
  CloseCircleFillIcon,
  CloseIcon,
  DeleteIcon,
  CopyIcon,
  DragIcon,
  EditIcon,
  ExternalLinkIcon,
  LeftSideBarToggleIcon,
  MenuIcon,
  PushPinIcon,
  QuestionListIcon,
  RankingIcon,
  SettingsIcon,
  ShutDownIcon,
  SmallThreeDotIcon,
  StarIcon,
  TableIcon,
  TrashIcon,
  UploadIcon,
} from '.'

export default {
  component: null,
}

export {
  AddIcon,
  AlignLeftIcon,
  AlignMiddleIcon,
  AlignRightIcon,
  ArrowDownIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  BrushIcon,
  CheckIcon,
  ClipBoardIcon,
  ClockIcon,
  CloseCircleFillIcon,
  CloseIcon,
  DeleteIcon,
  CopyIcon,
  DragIcon,
  EditIcon,
  ExternalLinkIcon,
  LeftSideBarToggleIcon,
  MenuIcon,
  PushPinIcon,
  QuestionListIcon,
  RankingIcon,
  SettingsIcon,
  ShutDownIcon,
  SmallThreeDotIcon,
  StarIcon,
  TableIcon,
  TrashIcon,
  UploadIcon,
}
