export const languages = {
  'af': {
    description: 'Afrikaans',
    nativedescription: 'Afrikaans',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
    momentjs: 'af',
  },
  'sq': {
    description: 'Albanian',
    nativedescription: 'Shqipe',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
    momentjs: 'sq',
  },
  'am': {
    description: 'Amharic',
    nativedescription: '&#4768;&#4635;&#4653;&#4763;',
    rtl: false,
    dateformat: 2,
    radixpoint: 1,
    momentjs: null,
  },
  'ar': {
    description: 'Arabic',
    nativedescription: '&#1593;&#1614;&#1585;&#1614;&#1576;&#1610;&#1618;',
    rtl: true,
    dateformat: 2,
    radixpoint: 0,
    momentjs: 'ar',
  },
  'hy': {
    description: 'Armenian',
    nativedescription: '&#1392;&#1377;&#1397;&#1381;&#1408;&#1381;&#1398;',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
    momentjs: 'hy-am',
  },
  'az': {
    description: 'Azerbaijani',
    nativedescription: 'Azerbaycanca',
    rtl: false,
    dateformat: 5,
    radixpoint: 1,
    momentjs: 'az',
  },
  'eu': {
    description: 'Basque',
    nativedescription: 'Euskara',
    rtl: false,
    dateformat: 3,
    radixpoint: 1,
    momentjs: 'eu',
  },
  'be': {
    description: 'Belarusian',
    nativedescription:
      '&#1041;&#1077;&#1083;&#1072;&#1088;&#1091;&#1089;&#1082;&#1110;',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
    momentjs: 'be',
  },
  'bn': {
    description: 'Bengali',
    nativedescription: '&#2476;&#2494;&#2434;&#2482;&#2494;',
    rtl: false,
    dateformat: 2,
    radixpoint: 0,
    momentjs: 'bn',
  },
  'bs': {
    description: 'Bosnian',
    nativedescription: 'Bosanski',
    rtl: false,
    dateformat: 4,
    radixpoint: 0,
    momentjs: 'bs',
  },
  'bg': {
    description: 'Bulgarian',
    nativedescription:
      '&#x0411;&#x044a;&#x043b;&#x0433;&#x0430;&#x0440;&#x0441;&#x043a;&#x0438;',
    rtl: false,
    dateformat: 1,
    radixpoint: 0,
    momentjs: 'bg',
  },
  'ca': {
    description: 'Catalan',
    nativedescription: 'Catal&#224;',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
    momentjs: 'ca',
  },
  'ceb': {
    description: 'Cebuano',
    nativedescription: 'Cebuano',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
  },
  'ny': {
    description: 'Chichewa',
    nativedescription: 'Chichewa',
    rtl: false,
    dateformat: 5,
    radixpoint: 0,
  },
  'zh-Hans': {
    description: 'Chinese (Simplified)',
    nativedescription: '&#31616;&#20307;&#20013;&#25991;',
    rtl: false,
    dateformat: 6,
    radixpoint: 0,
    momentjs: 'zh-cn',
  },
  'zh-Hant-HK': {
    description: 'Chinese (Traditional; Hong Kong)',
    nativedescription: '&#32321;&#39636;&#20013;&#25991;&#35486;&#31995;',
    rtl: false,
    dateformat: 6,
    radixpoint: 0,
    momentjs: 'zh-hk',
  },
  'zh-Hant-TW': {
    description: 'Chinese (Traditional; Taiwan)',
    nativedescription:
      '&#32321;&#39636;&#20013;&#25991;&#65288;&#21488;&#28771;&#65289;',
    rtl: false,
    dateformat: 6,
    radixpoint: 0,
    momentjs: 'zh-tw',
  },
  'hat': {
    description: 'Creole (Haitian)',
    nativedescription: 'Kreyòl ayisyen',
    rtl: false,
    dateformat: 6,
    radixpoint: 1,
    cldr: 'fr_ht',
  },
  'hr': {
    description: 'Croatian',
    nativedescription: 'Hrvatski',
    rtl: false,
    dateformat: 4,
    radixpoint: 1,
    momentjs: 'hr',
  },
  'cs': {
    description: 'Czech',
    nativedescription: '&#x010c;esky',
    rtl: false,
    dateformat: 4,
    radixpoint: 1,
    momentjs: 'cs',
  },
  'cs-informal': {
    description: 'Czech (informal)',
    nativedescription: '&#x010c;esky neform&aacute;ln&iacute;',
    rtl: false,
    dateformat: 4,
    radixpoint: 1,
    cldr: 'cs',
    momentjs: 'cs',
  },
  'da': {
    description: 'Danish',
    nativedescription: 'Dansk',
    rtl: false,
    dateformat: 2,
    radixpoint: 1,
    momentjs: 'da',
  },
  'prs': {
    description: 'Dari',
    nativedescription: '&#1583;&#1585;&#1740;',
    rtl: true,
    dateformat: 6,
    radixpoint: 0,
    cldr: 'fa_af',
    momentjs: null,
  },
  'nl': {
    description: 'Dutch',
    nativedescription: 'Nederlands',
    rtl: false,
    dateformat: 2,
    radixpoint: 1,
    momentjs: 'nl',
  },
  'nl-informal': {
    description: 'Dutch (informal)',
    nativedescription: 'Nederlands (informeel)',
    rtl: false,
    dateformat: 2,
    radixpoint: 1,
    cldr: 'nl',
    momentjs: 'nl',
  },
  'en': {
    description: 'English',
    nativedescription: 'English',
    rtl: false,
    dateformat: 9,
    radixpoint: 0,
    momentjs: 'en',
  },
  'et': {
    description: 'Estonian',
    nativedescription: 'Eesti',
    rtl: false,
    dateformat: 4,
    radixpoint: 1,
    momentjs: 'et',
  },
  'fil': {
    description: 'Filipino',
    nativedescription: 'Wikang Filipino',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
    momentjs: 'fil',
  },
  'fi': {
    description: 'Finnish',
    nativedescription: 'Suomi',
    rtl: false,
    dateformat: 4,
    radixpoint: 1,
    momentjs: 'fi',
  },
  'fr': {
    description: 'French',
    nativedescription: 'Fran&#231;ais',
    rtl: false,
    dateformat: 5,
    radixpoint: 1,
    momentjs: 'fr',
  },
  'ful': {
    description: 'Fula',
    nativedescription: 'Fulfulde',
    rtl: false,
    dateformat: 5,
    radixpoint: 1,
    cldr: 'ff',
    momentjs: null,
  },
  'gl': {
    description: 'Galician',
    nativedescription: 'Galego',
    rtl: false,
    dateformat: 5,
    radixpoint: 1,
    momentjs: 'gl',
  },
  'ka': {
    description: 'Georgian',
    nativedescription:
      '&#4325;&#4304;&#4320;&#4311;&#4323;&#4314;&#4312; &#4308;&#4316;&#4304;',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
    momentjs: 'ka',
  },
  'de': {
    description: 'German',
    nativedescription: 'Deutsch',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
    momentjs: 'de',
  },
  'de-easy': {
    description: 'German (easy)',
    nativedescription: 'Deutsch - Leichte Sprache',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
    cldr: 'de',
    momentjs: 'de',
  },
  'de-informal': {
    description: 'German (informal)',
    nativedescription: 'Deutsch (Du)',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
    cldr: 'de',
    momentjs: 'de',
  },
  'el': {
    description: 'Greek',
    nativedescription: '&#917;&#955;&#955;&#951;&#957;&#953;&#954;&#940;',
    rtl: false,
    dateformat: 8,
    radixpoint: 1,
    momentjs: 'el',
  },
  'kal': {
    description: 'Greenlandic',
    nativedescription: 'Kalaallisut',
    rtl: false,
    dateformat: 2,
    radixpoint: 1,
    momentjs: null,
  },
  'gu': {
    description: 'Gujarati',
    nativedescription: '&#2711;&#2753;&#2716;&#2736;&#2750;&#2724;&#2752;',
    rtl: false,
    dateformat: 2,
    radixpoint: 0,
    momentjs: 'gu',
  },
  'ha': {
    description: 'Hausa',
    nativedescription: 'Hausa',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
  },
  'haz': {
    description: 'Hazaragi',
    nativedescription: '&#x622;&#x632;&#x631;&#x6AF;&#x6CC;',
    rtl: true,
    dateformat: 2,
    radixpoint: 0,
    momentjs: 'fa',
    cldr: 'fa',
  },
  'he': {
    description: 'Hebrew',
    nativedescription: ' &#1506;&#1489;&#1512;&#1497;&#1514;',
    rtl: true,
    dateformat: 5,
    radixpoint: 0,
    momentjs: 'he',
  },
  'hil': {
    description: 'Hiligaynon',
    nativedescription: 'Ilonggo',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
  },
  'hi': {
    description: 'Hindi',
    nativedescription: '&#2361;&#2367;&#2344;&#2381;&#2342;&#2368;',
    rtl: false,
    dateformat: 2,
    radixpoint: 0,
    momentjs: 'hi',
  },
  'hu': {
    description: 'Hungarian',
    nativedescription: 'Magyar',
    rtl: false,
    dateformat: 6,
    radixpoint: 1,
    momentjs: 'hu',
  },
  'is': {
    description: 'Icelandic',
    nativedescription: '&#237;slenska',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
    momentjs: 'is',
  },
  'ilo': {
    description: 'Ilocano',
    nativedescription: 'Ilokano',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
  },
  'id': {
    description: 'Indonesian',
    nativedescription: 'Bahasa Indonesia',
    rtl: false,
    dateformat: 5,
    radixpoint: 1,
    momentjs: 'id',
  },
  'ike': {
    description: 'Inuktitut',
    nativedescription: '&#x1403;&#x14C4;&#x1483;&#x144E;&#x1450;&#x1466;',
    rtl: false,
    dateformat: 5,
    radixpoint: 1,
    momentjs: null,
  },
  'ie': {
    description: 'Irish',
    nativedescription: 'Gaeilge',
    rtl: false,
    dateformat: 2,
    radixpoint: 0,
    cldr: 'ga',
    momentjs: 'ga',
  },
  'it': {
    description: 'Italian',
    nativedescription: 'Italiano',
    rtl: false,
    dateformat: 5,
    radixpoint: 1,
    momentjs: 'it',
  },
  'it-informal': {
    description: 'Italian (informal)',
    nativedescription: 'Italiano (informale)',
    rtl: false,
    dateformat: 5,
    radixpoint: 1,
    cldr: 'it',
    momentjs: 'it',
  },
  'ja': {
    description: 'Japanese',
    nativedescription: '&#x65e5;&#x672c;&#x8a9e;',
    rtl: false,
    dateformat: 6,
    radixpoint: 0,
    momentjs: 'ja',
  },
  'kn': {
    description: 'Kannada',
    nativedescription: '&#xC95;&#xCA8;&#xCCD;&#xCA8;&#xCA1;',
    rtl: false,
    dateformat: 2,
    radixpoint: 0,
    momentjs: 'kn',
  },
  'kk': {
    description: 'Kazakh',
    nativedescription: 'Qazaq&#351;a',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
    momentjs: 'kk',
  },
  'km': {
    description: 'Khmer',
    nativedescription: 'Khmer',
    rtl: false,
    dateformat: 5,
    radixpoint: 1,
    cldr: 'km',
    momentjs: null,
  },
  'rw': {
    description: 'Kinyarwanda',
    nativedescription: 'Kinyarwanda',
    rtl: false,
    dateformat: 5,
    radixpoint: 1,
    momentjs: null,
  },
  'run': {
    description: 'Kirundi',
    nativedescription: 'Ikirundi',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
    momentjs: null,
  },
  'ko': {
    description: 'Korean',
    nativedescription: '&#54620;&#44397;&#50612;',
    rtl: false,
    dateformat: 7,
    radixpoint: 0,
    momentjs: 'ko',
  },
  'kmr': {
    description: 'Kurdish (Kurmanji)',
    nativedescription: 'Kurmanc&#xEE;',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
    cldr: 'ku',
    momentjs: 'ku',
  },
  'ckb': {
    description: 'Kurdish (Sorani)',
    nativedescription:
      '&#1705;&#1608;&#1585;&#1583;&#1740;&#1740; &#1606;&#1575;&#1608;&#1749;&#1606;&#1583;&#1740;',
    rtl: true,
    dateformat: 1,
    radixpoint: 1,
    cldr: 'ku',
    momentjs: 'ku',
  },
  'ky': {
    description: 'Kyrgyz',
    nativedescription:
      '&#1050;&#1099;&#1088;&#1075;&#1099;&#1079;&#1095;&#1072;',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
    momentjs: 'ky',
  },
  'lv': {
    description: 'Latvian',
    nativedescription: 'Latvie&#353;u',
    rtl: false,
    dateformat: 6,
    radixpoint: 1,
    momentjs: 'lv',
  },
  'lt': {
    description: 'Lithuanian',
    nativedescription: 'Lietuvi&#371;',
    rtl: false,
    dateformat: 6,
    radixpoint: 1,
    momentjs: 'lt',
  },
  'lb': {
    description: 'Luxembourgish',
    nativedescription: 'L&#235;tzebuergesch',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
    cldr: 'fr_lu',
    momentjs: 'lb',
  },
  'mk': {
    description: 'Macedonian',
    nativedescription:
      '&#1052;&#1072;&#1082;&#1077;&#1076;&#1086;&#1085;&#1089;&#1082;&#1080;',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
    momentjs: 'mk',
  },
  'ms': {
    description: 'Malay',
    nativedescription: 'Bahasa Melayu',
    rtl: false,
    dateformat: 1,
    radixpoint: 0,
    momentjs: 'ms',
  },
  'ml': {
    description: 'Malayalam',
    nativedescription: 'Malay&#257;&#7735;a&#7745;',
    rtl: false,
    dateformat: 2,
    radixpoint: 0,
    momentjs: 'ml',
  },
  'mt': {
    description: 'Maltese',
    nativedescription: 'Malti',
    rtl: false,
    dateformat: 1,
    radixpoint: 0,
    momentjs: 'mt',
  },
  'mr': {
    description: 'Marathi',
    nativedescription: '&#2350;&#2352;&#2366;&#2336;&#2368;',
    rtl: false,
    dateformat: 2,
    radixpoint: 0,
    momentjs: 'mr',
  },
  'mn': {
    description: 'Mongolian',
    nativedescription: '&#1052;&#1086;&#1085;&#1075;&#1086;&#1083;',
    rtl: false,
    dateformat: 3,
    radixpoint: 0,
    momentjs: 'mn',
  },
  'cnr': {
    description: 'Montenegrin',
    nativedescription: 'Crnogorski',
    rtl: false,
    dateformat: 4,
    radixpoint: 1,
    cldr: 'sr_Latn_ME',
    momentjs: 'me',
  },
  'mya': {
    description: 'Myanmar (Burmese)',
    nativedescription:
      '&#4121;&#4156;&#4116;&#4154;&#4121;&#4140;&#4120;&#4140;&#4126;&#4140;',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
    momentjs: 'my',
  },
  'ne': {
    description: 'Nepali',
    nativedescription: 'Nepali',
    rtl: false,
    dateformat: 6,
    radixpoint: 0,
    momentjs: 'ne',
  },
  'nb': {
    description: 'Norwegian (Bokmal)',
    nativedescription: 'Norsk Bokm&#229;l',
    rtl: false,
    dateformat: 4,
    radixpoint: 1,
    momentjs: 'nb',
  },
  'nn': {
    description: 'Norwegian (Nynorsk)',
    nativedescription: 'Norsk Nynorsk',
    rtl: false,
    dateformat: 4,
    radixpoint: 1,
    momentjs: 'nn',
  },
  'oc': {
    description: 'Occitan',
    nativedescription: "Lenga d'&#242;c",
    rtl: false,
    dateformat: 5,
    radixpoint: 1,
    momentjs: 'oc-lnc',
  },
  'ory': {
    description: 'Odia',
    nativedescription: '&#xB13;&#xB21;&#xB3C;&#xB3F;&#xB06;',
    rtl: false,
    dateformat: 5,
    radixpoint: 1,
  },
  'pap-CW': {
    description: 'Papiamento (Curaçao &amp; Bonaire)',
    nativedescription: 'Papiamentu',
    rtl: false,
    dateformat: 2,
    radixpoint: 1,
    cldr: 'en',
    momentjs: null,
  },
  'ps': {
    description: 'Pashto',
    nativedescription: '&#1662;&#1690;&#1578;&#1608;',
    rtl: true,
    dateformat: 6,
    radixpoint: 0,
    momentjs: null,
  },
  'fa': {
    description: 'Persian',
    nativedescription: '&#1601;&#1575;&#1585;&#1587;&#1740;',
    rtl: true,
    dateformat: 6,
    radixpoint: 0,
    momentjs: 'fa',
  },
  'pl': {
    description: 'Polish',
    nativedescription: 'Polski',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
    momentjs: 'pl',
  },
  'pl-informal': {
    description: 'Polish (Informal)',
    nativedescription: 'Polski (nieformalny)',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
    cldr: 'pl',
    momentjs: 'pl',
  },
  'pt': {
    description: 'Portuguese',
    nativedescription: 'Portugu&#234;s',
    rtl: false,
    dateformat: 5,
    radixpoint: 1,
    momentjs: 'pt',
  },
  'pt-BR': {
    description: 'Portuguese (Brazilian)',
    nativedescription: 'Portugu&#234;s do Brasil',
    rtl: false,
    dateformat: 5,
    radixpoint: 1,
    momentjs: 'pt-br',
  },
  'pa': {
    description: 'Punjabi',
    nativedescription: '&#2602;&#2672;&#2588;&#2622;&#2604;&#2624;',
    rtl: false,
    dateformat: 2,
    radixpoint: 0,
    momentjs: 'pa-in',
  },
  'ro': {
    description: 'Romanian',
    nativedescription: 'Rom&#226;na',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
    momentjs: 'ro',
  },
  'roh': {
    description: 'Romansh',
    nativedescription: 'Rumantsch',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
    momentjs: null,
  },
  'ru': {
    description: 'Russian',
    nativedescription: '&#1056;&#1091;&#1089;&#1089;&#1082;&#1080;&#1081;',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
    momentjs: 'ru',
  },
  'smi': {
    description: 'Sami (Northern)',
    nativedescription: 'Davvisámegiella',
    rtl: false,
    dateformat: 4,
    radixpoint: 1,
    momentjs: 'sme',
  },
  'sr': {
    description: 'Serbian (Cyrillic)',
    nativedescription: '&#1057;&#1088;&#1087;&#1089;&#1082;&#1080;',
    rtl: false,
    dateformat: 4,
    radixpoint: 1,
    momentjs: 'sr-cyrl',
  },
  'sr-Latn': {
    description: 'Serbian (Latin)',
    nativedescription: 'Srpski',
    rtl: false,
    dateformat: 4,
    radixpoint: 1,
    momentjs: 'sr',
  },
  'si': {
    description: 'Sinhala',
    nativedescription: '&#3523;&#3538;&#3458;&#3524;&#3517;',
    rtl: false,
    dateformat: 5,
    radixpoint: 0,
    momentjs: 'si',
  },
  'sk': {
    description: 'Slovak',
    nativedescription: 'Sloven&#269;ina',
    rtl: false,
    dateformat: 4,
    radixpoint: 1,
    momentjs: 'sk',
  },
  'sl': {
    description: 'Slovenian',
    nativedescription: 'Sloven&#353;&#269;ina',
    rtl: false,
    dateformat: 4,
    radixpoint: 1,
    momentjs: 'sl',
  },
  'so': {
    description: 'Somali',
    nativedescription: 'Af-Soomaali',
    rtl: false,
    dateformat: 9,
    radixpoint: 1,
    momentjs: null,
  },
  'es': {
    description: 'Spanish',
    nativedescription: 'Espa&#241;ol',
    rtl: false,
    dateformat: 5,
    radixpoint: 1,
    momentjs: 'es',
  },
  'es-AR': {
    description: 'Spanish (Argentina)',
    nativedescription: 'Espa&#241;ol rioplatense',
    rtl: false,
    dateformat: 5,
    radixpoint: 0,
    momentjs: 'es',
  },
  'es-AR-informal': {
    description: 'Spanish (Argentina) (Informal)',
    nativedescription: 'Espa&#241;ol rioplatense informal',
    rtl: false,
    dateformat: 5,
    radixpoint: 0,
    cldr: 'es-AR',
    momentjs: 'es',
  },
  'es-CL': {
    description: 'Spanish (Chile)',
    nativedescription: 'Espa&#241;ol chileno',
    rtl: false,
    dateformat: 5,
    radixpoint: 0,
    momentjs: 'es',
  },
  'es-CO': {
    description: 'Spanish (Colombia)',
    nativedescription: 'Espa&#241;ol colombiano',
    rtl: false,
    dateformat: 5,
    radixpoint: 0,
    momentjs: 'es',
  },
  'es-MX': {
    description: 'Spanish (Mexico)',
    nativedescription: 'Espa&#241;ol mexicano',
    rtl: false,
    dateformat: 5,
    radixpoint: 0,
    momentjs: 'es',
  },
  'es-informal': {
    description: 'Spanish (informal)',
    nativedescription: 'Espa&#241;ol (informal)',
    rtl: false,
    dateformat: 5,
    radixpoint: 1,
    cldr: 'es',
    momentjs: 'es',
  },
  'swh': {
    description: 'Swahili',
    nativedescription: 'Kiswahili',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
    cldr: 'sw',
    momentjs: 'sw',
  },
  'sv': {
    description: 'Swedish',
    nativedescription: 'Svenska',
    rtl: false,
    dateformat: 6,
    radixpoint: 1,
    momentjs: 'sv',
  },
  'tl': {
    description: 'Tagalog',
    nativedescription: 'Tagalog',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
    momentjs: 'tl-ph',
  },
  'tg': {
    description: 'Tajik',
    nativedescription: '&#x422;&#x43E;&#x4B7;&#x438;&#x43A;&#x4E3;',
    rtl: false,
    dateformat: 6,
    radixpoint: 0,
    momentjs: 'tg',
  },
  'ta': {
    description: 'Tamil',
    nativedescription: '&#2980;&#2990;&#3007;&#2996;&#3021;',
    rtl: false,
    dateformat: 2,
    radixpoint: 0,
    momentjs: 'ta',
  },
  'te': {
    description: 'Telugu',
    nativedescription: '&#xC24;&#xC46;&#xC32;&#xC41;&#xC17;&#xC41;',
    rtl: false,
    dateformat: 2,
    radixpoint: 0,
    momentjs: 'te',
  },
  'th': {
    description: 'Thai',
    nativedescription: '&#3616;&#3634;&#3625;&#3634;&#3652;&#3607;&#3618;',
    rtl: false,
    dateformat: 5,
    radixpoint: 0,
    momentjs: 'th',
  },
  'ti': {
    description: 'Tigrinya',
    nativedescription: '&#x1275;&#x130d;&#x122d;&#x129b;',
    rtl: false,
    dateformat: 9,
    radixpoint: 0,
    momentjs: null,
  },
  'tr': {
    description: 'Turkish',
    nativedescription: 'T&#252;rk&#231;e',
    rtl: false,
    dateformat: 5,
    radixpoint: 1,
    momentjs: 'tr',
  },
  'uk': {
    description: 'Ukrainian',
    nativedescription:
      '&#x423;&#x43A;&#x440;&#x430;&#x457;&#x43D;&#x441;&#x44C;&#x43A;&#x430;',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
    momentjs: 'uk',
  },
  'ur': {
    description: 'Urdu',
    nativedescription: '&#1575;&#1585;&#1583;&#1608;',
    rtl: true,
    dateformat: 2,
    radixpoint: 0,
    momentjs: 'ur',
  },
  'ug': {
    description: 'Uyghur',
    nativedescription: 'ئۇيغۇرچە',
    rtl: true,
    dateformat: 6,
    radixpoint: 0,
    momentjs: 'ug-cn',
  },
  'uz': {
    description: 'Uzbek',
    nativedescription: "O'zbek",
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
    momentjs: 'uz',
  },
  'ca-valencia': {
    description: 'Valencian',
    nativedescription: 'Valenci&#224;',
    rtl: false,
    dateformat: 1,
    radixpoint: 1,
    cldr: 'ca',
    momentjs: 'ca',
  },
  'vi': {
    description: 'Vietnamese',
    nativedescription: 'Ti&#7871;ng Vi&#7879;t',
    rtl: false,
    dateformat: 5,
    radixpoint: 1,
    momentjs: 'vi',
  },
  'cy': {
    description: 'Welsh',
    nativedescription: 'Cymraeg',
    rtl: false,
    dateformat: 5,
    radixpoint: 0,
    momentjs: 'cy',
  },
  'xho': {
    description: 'Xhosa',
    nativedescription: 'isiXhosa',
    rtl: false,
    dateformat: 5,
    radixpoint: 1,
    momentjs: 'null',
  },
  'sah': {
    description: 'Yakut',
    nativedescription:
      '&#x421;&#x430;&#x445;&#x430; &#x442;&#x44B;&#x43B;&#x430;',
    rtl: false,
    dateformat: 5,
    radixpoint: 1,
    momentjs: 'null',
  },
  'yor': {
    description: 'Yoruba',
    nativedescription: '&#xC8;d&#xE8; Yor&#xF9;b&#xE1;',
    rtl: false,
    dateformat: 5,
    radixpoint: 1,
    momentjs: null,
  },
  'zu': {
    description: 'Zulu',
    nativedescription: 'isiZulu',
    rtl: false,
    dateformat: 5,
    radixpoint: 1,
    momentjs: null,
  },
}
